### ISSUE TITLE
issuer name of PCSID

### ISSUE THREAD

**Issue by ajaybalachandran** [Repzo/zatca-xml-js#3]
Is the format of the issuer name(core API) correct as provided below: 
`<ds:X509IssuerName>CN=PRZEINVOICESCA4-CA, DC=extgazt, DC=gov, DC=local</ds:X509IssuerName>`

The API responses do not show any errors regarding this. However, the ZATCA web-based validator indicates that it's a wrong serial number. Could you please confirm if the format of the issuer name is correct, or provide a valid format if it's incorrect?

**Comment by moAlnatour** [comment]
This issuer name format 
<ds:X509IssuerName>CN=PRZEINVOICESCA4-CA, DC=extgazt, DC=gov, DC=local</ds:X509IssuerName>
is returned from zatca when use Production CSID (Onboarding) API .

to avoid error in  ZATCA web-based validator using PCSID when sign invoice,

please install latest version "0.1.1"
```javascript
    const { signed_invoice_string, invoice_hash, qr } = egs.signInvoice(
      invoice,
      true // should be equal true when need to sign with PCSID
    );
```
